### ISSUE TITLE
Pin / unpin option

### ISSUE THREAD

**Issue by iH1dek1** [Insomn1ac/hammerfell_tg_bot#2]
Can I add the function of pinning bot messages?
And unpin after the new launch of the labyrinth.

**Comment by Insomn1ac** [comment]
Now bot will pin user message with certain keyword, then send a duplicate of a user message to chat (with user' nickname as sender of original message). When bot hears a certain keyword, responsible for launching the labyrinth - he will unpin previously pinned message.
